version: '3'
services:
  postgresql:
    image: postgres
    container_name: nest-postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DATABASE=root
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-nest
    ports:
      - "6379:6379"